version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    container_name: dev_postgres
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    env_file: ".env"
    volumes:
      - grading_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  grading_data:
